# Generated by Django 2.2 on 2021-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainimage',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
