# Generated by Django 2.2 on 2021-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0003_auto_20210817_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(max_length=800, verbose_name='Description'),
        ),
    ]
