# Generated by Django 2.2 on 2021-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0005_auto_20210829_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
    ]
